image: docker:latest

services:
  - name: docker:dind
    command: ["--experimental"]

stages:
  - build

.docker_build_template: &docker_build_template |
  docker build --squash --pull .


build_job:
  stage: build
  script:
    - *docker_build_template
