insert into permission(id,version,action_name,entity_name,scope,code_name) values (1,0,'ALL','ALL','ALL','ALL_ALL_ALL');
insert into permission(id,version,action_name,entity_name,scope,code_name) values (2,0,'READ','ALL','ALL','READ_ALL_ALL');

insert into permission(id,version,entity_name,action_name,scope,code_name) values(12,0,'PROJECT','READ','ALL','READ_ALL_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(13,0,'PROJECT','READ','ASSIGNED','READ_ASSIGNED_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(14,0,'PROJECT','CREATE','ALL','CREATE_ALL_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(16,0,'PROJECT','UPDATE','ALL','UPDATE_ALL_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(17,0,'PROJECT','UPDATE','ASSIGNED','UPDATE_ASSIGNED_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(18,0,'PROJECT','DELETE','ALL','DELETE_ALL_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(19,0,'PROJECT','DELETE','ASSIGNED','DELETE_ASSIGNED_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(20,0,'PROJECT','ASSIGN','ALL','ASSIGN_ALL_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(21,0,'PROJECT','ASSIGN','ASSIGNED','ASSIGN_ASSIGNED_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(22,0,'PROJECT','VERIFY','ALL','VERIFY_ALL_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(23,0,'PROJECT','VERIFY','ASSIGNED','VERIFY_ASSIGNED_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(24,0,'PROJECT','APPROVE','ALL','APPROVE_ALL_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(25,0,'PROJECT','APPROVE','ASSIGNED','APPROVE_ASSIGNED_PROJECT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(28,0,'TASK','READ','ALL','READ_ALL_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(29,0,'TASK','READ','ASSIGNED','READ_ASSIGNED_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(30,0,'TASK','CREATE','ALL','CREATE_ALL_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(32,0,'TASK','UPDATE','ALL','UPDATE_ALL_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(33,0,'TASK','UPDATE','ASSIGNED','UPDATE_ASSIGNED_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(34,0,'TASK','DELETE','ALL','DELETE_ALL_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(35,0,'TASK','DELETE','ASSIGNED','DELETE_ASSIGNED_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(36,0,'TASK','ASSIGN','ALL','ASSIGN_ALL_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(37,0,'TASK','ASSIGN','ASSIGNED','ASSIGN_ASSIGNED_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(38,0,'TASK','VERIFY','ALL','VERIFY_ALL_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(39,0,'TASK','VERIFY','ASSIGNED','VERIFY_ASSIGNED_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(40,0,'TASK','APPROVE','ALL','APPROVE_ALL_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(41,0,'TASK','APPROVE','ASSIGNED','APPROVE_ASSIGNED_TASK');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(44,0,'HOUSE','READ','ALL','READ_ALL_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(45,0,'HOUSE','READ','ASSIGNED','READ_ASSIGNED_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(46,0,'HOUSE','CREATE','ALL','CREATE_ALL_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(48,0,'HOUSE','UPDATE','ALL','UPDATE_ALL_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(49,0,'HOUSE','UPDATE','ASSIGNED','UPDATE_ASSIGNED_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(50,0,'HOUSE','DELETE','ALL','DELETE_ALL_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(51,0,'HOUSE','DELETE','ASSIGNED','DELETE_ASSIGNED_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(54,0,'HOUSE','VERIFY','ALL','VERIFY_ALL_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(55,0,'HOUSE','VERIFY','ASSIGNED','VERIFY_ASSIGNED_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(56,0,'HOUSE','APPROVE','ALL','APPROVE_ALL_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(57,0,'HOUSE','APPROVE','ASSIGNED','APPROVE_ASSIGNED_HOUSE');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(60,0,'STREET','READ','ALL','READ_ALL_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(61,0,'STREET','READ','ASSIGNED','READ_ASSIGNED_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(62,0,'STREET','CREATE','ALL','CREATE_ALL_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(64,0,'STREET','UPDATE','ALL','UPDATE_ALL_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(65,0,'STREET','UPDATE','ASSIGNED','UPDATE_ASSIGNED_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(66,0,'STREET','DELETE','ALL','DELETE_ALL_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(67,0,'STREET','DELETE','ASSIGNED','DELETE_ASSIGNED_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(70,0,'STREET','VERIFY','ALL','VERIFY_ALL_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(71,0,'STREET','VERIFY','ASSIGNED','VERIFY_ASSIGNED_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(72,0,'STREET','APPROVE','ALL','APPROVE_ALL_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(73,0,'STREET','APPROVE','ASSIGNED','APPROVE_ASSIGNED_STREET');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(76,0,'BOQ','READ','ALL','READ_ALL_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(77,0,'BOQ','READ','ASSIGNED','READ_ASSIGNED_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(78,0,'BOQ','CREATE','ALL','CREATE_ALL_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(80,0,'BOQ','UPDATE','ALL','UPDATE_ALL_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(81,0,'BOQ','UPDATE','ASSIGNED','UPDATE_ASSIGNED_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(82,0,'BOQ','DELETE','ALL','DELETE_ALL_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(83,0,'BOQ','DELETE','ASSIGNED','DELETE_ASSIGNED_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(84,0,'BOQ','ASSIGN','ALL','ASSIGN_ALL_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(85,0,'BOQ','ASSIGN','ASSIGNED','ASSIGN_ASSIGNED_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(86,0,'BOQ','VERIFY','ALL','VERIFY_ALL_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(87,0,'BOQ','VERIFY','ASSIGNED','VERIFY_ASSIGNED_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(88,0,'BOQ','APPROVE','ALL','APPROVE_ALL_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(89,0,'BOQ','APPROVE','ASSIGNED','APPROVE_ASSIGNED_BOQ');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(92,0,'PAYMENT','READ','ALL','READ_ALL_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(94,0,'PAYMENT','CREATE','ALL','CREATE_ALL_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(96,0,'PAYMENT','UPDATE','ALL','UPDATE_ALL_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(97,0,'PAYMENT','UPDATE','ASSIGNED','UPDATE_ASSIGNED_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(98,0,'PAYMENT','DELETE','ALL','DELETE_ALL_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(99,0,'PAYMENT','DELETE','ASSIGNED','DELETE_ASSIGNED_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(100,0,'PAYMENT','ASSIGN','ALL','ASSIGN_ALL_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(101,0,'PAYMENT','ASSIGN','ASSIGNED','ASSIGN_ASSIGNED_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(102,0,'PAYMENT','VERIFY','ALL','VERIFY_ALL_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(103,0,'PAYMENT','VERIFY','ASSIGNED','VERIFY_ASSIGNED_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(104,0,'PAYMENT','APPROVE','ALL','APPROVE_ALL_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(105,0,'PAYMENT','APPROVE','ASSIGNED','APPROVE_ASSIGNED_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(106,0,'PAYMENT','REVIEW','ALL','REVIEW_ALL_PAYMENT');
insert into permission(id,version,entity_name,action_name,scope,code_name) values(107,0,'PAYMENT','REVIEW','ASSIGNED','REVIEW_ASSIGNED_PAYMENT');

insert into user_role(id,`version`,name) values (1,0,'admin');

insert into user_role_permissions values (1,1);

insert into users(id,`version`,user_name,email,`password`,status,role_id) values (1,0,'admin','admin@mail.com','$2a$10$BCcz5D3246cIiRbaaNzDiO5pz4.hMYNl5/YHFo8sYkECLZUGmBo22','ACTIVE',1);